DROP DATABASE IF EXISTS db_employee_cms;
CREATE DATABASE db_employee_cms;

USE db_employee_cms;

CREATE TABLE departments (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL,
  PRIMARY KEY (id));

CREATE TABLE roles (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(30) NOT NULL,
  salary DECIMAL NOT NULL,
  department_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  INDEX fk_roles_1_idx (department_id ASC) VISIBLE,
  CONSTRAINT fk_roles_1 
    FOREIGN KEY (department_id)
    REFERENCES departments (id)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);

CREATE TABLE employees (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  role_id INT UNSIGNED NOT NULL,
  manager_id INT UNSIGNED NULL,
  PRIMARY KEY (id));

  ALTER TABLE employees
  ADD FOREIGN KEY (role_id) REFERENCES roles(id);
  ON DELETE CASCADE
  ON UPDATE NO ACTION,

  ALTER TABLE employees
  ADD FOREIGN KEY (manager_id) REFERENCES employees(id);
  ON DELETE CASCADE
  ON UPDATE NO ACTION,